name: Build Flutter APKs

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
          cache: true

      # Run flutter doctor
      - run: flutter doctor -v

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build unsigned APK
      - name: Build unsigned APK
        run: flutter build apk --split-per-abi --release

      # Build unsigned App Bundle
      - name: Build unsigned App Bundle
        run: flutter build appbundle --release

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/apk/release/*-release.apk
            build/app/outputs/bundle/release/app-release.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            build/app/outputs/apk/release/*-release.apk
            build/app/outputs/bundle/release/app-release.aab
          retention-days: 7